### ISSUE TITLE
Uncaught type error when trying with newer version dependencies. 

### ISSUE THREAD

**Issue by entest-hai** [mtliendo/seattle-team-visit-map#1]
The provided package.json works well, I can reproduce. However, when I try with newer dependencies as below, I got errors. I think the errors due to MapView component because when I change to Map from react-map-gl, it works
```json
{
  "name": "amplify-studio-demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^3.0.4",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^4.3.27",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-map-gl": "^7.0.17",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}


error 
```bash
Uncaught TypeError: Cannot destructure property 'map' of '(0 , react__WEBPACK_IMPORTED_MODULE_0__.useContext)(...)' as it is null.
    at Marker (marker.ts:87:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```
```

**Comment by richstimson** [comment]
@entest-hai The issue is the <Marker> component as I found from your issue here: https://github.com/aws-amplify/amplify-ui/issues/2270. This solution worked for me after deleting and recreating node_modules and package.lock.json. 

Also note that \<AmplifyProvider> in the sample code has been renamed to \<ThemeProvider> - see https://ui.docs.amplify.aws/react/theming/theme-provider

And <MapView> is now in @aws-amplify/ui-react-geo:
* import { MapView } from '@aws-amplify/ui-react-geo';
